spring.application.name=order-service
spring.datasource.url=jdbc:postgresql://localhost:5432/order_service
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=none

# Set the baseline to only show warnings and errors
logging.level.root=WARN

# Silence Spring's verbose internal logging
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR

# KEEP your own application's logs detailed
logging.level.com.tourist.microservices=DEBUG

server.port=8081

spring.output.ansi.enabled=ALWAYS
