spring.application.name=product-service
spring.data.mongodb.uri=mongodb://admin:admin123@localhost:6543/productService?authSource=admin
spring.docker.compose.enabled=false

# Set the baseline to only show warnings and errors
logging.level.root=WARN

# Silence Spring's verbose internal logging
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR

# KEEP your own application's logs detailed
logging.level.com.tourist.microservices=DEBUG

server.port=8080

spring.output.ansi.enabled=ALWAYS
